config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :index, :edit, :update]
  resources :books do
    resources :book_comments, only: [:create,:destroy]
    resource :favorites, only: [:create, :destroy]
  end
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :book_comments, dependent: :destroy
    validates :title, presence:true
    validates :body, presence:true,length: { minimum: 1, maximum: 200 }
    has_many :favorites, dependent: :destroy

    def favorited_by?(user)
        favorites.exists?(user_id: user.id)
    end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book

    validates :comment, presence:true,length: { maximum: 50 }

end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book
    validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence:true,length: { in: 2..20 }, uniqueness: true
  validates :introduction,length: { maximum: 50 }

  def get_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!, except: [:top, :about]


    def after_sign_in_path_for(resource)
        user_path(current_user)
    end

    def after_sign_in_path_for(resource)
        user_path(current_user)
    end

    def after_sign_out_path_for(resource)
      root_path
    end
    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
    def create
        book = Book.find(params[:book_id])
        comment = current_user.book_comments.new(comment_params)
        comment.book_id = book.id
        comment.user_id = current_user.id 
        comment.save
        redirect_to request.referer
    end

    def destroy
        BookComment.find(params[:id]).destroy
       redirect_to request.referer
    end

    
      private
    
      def comment_params
        params.require(:book_comment).permit(:comment)
      end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @user = current_user
    @books = Book.all
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = 'You have created book successfully.'
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = 'You have deleted book successfully.'
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.save
      flash[:notice] = 'You have updated book successfully.'
      redirect_to book_path(@book)
    else
      render :edit
    end
  end


  private

  def book_params 
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
        book = Book.find(params[:book_id])
        favorite = current_user.favorites.new(book_id: book.id)
        favorite.save
        redirect_to request.referer
    end
    
    def destroy
        book = Book.find(params[:book_id])
        favorite = current_user.favorites.find_by(book_id: book.id)
        favorite.destroy
        redirect_to request.referer
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit
    else 
      redirect_to user_path(current_user)
    end 
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      flash[:notice] = 'You have updated user successfully.'
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<br />
<div class='container'>
    <div class='row'>
        <div class='col-md-5 user__edit'>
            <h2>Editing Book</h2>
            <% if @book.errors.any? %>
                <%= @book.errors.count %>件のerrorが発生しました
                <ul>
                    <% @book.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            <% end %>
            <%= form_with model: @book do |f| %> 
                Title<br />
                <%= f.text_field :title %><br />          
                Opinion<br />
                <%= f.text_area :body %><br />

                <%= f.submit 'Update Book',class:'btn btn-success' %>
            <% end %><br />
            <%= link_to 'Show',book_path(@book) %> | <%= link_to 'Back',books_path %>
        </div>
    </div>
</div>

<br />
<p class='top__copy'>CopyRight Infratop.inc</p>

app/views/books/index.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-md-3'>
            <%= render 'users/user',user:@user %>
            <% if @book.errors.any? %>
                <%= @book.errors.count %>件のエラーが発生しました
                <ul>
                    <% @book.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            <% end %>
            <h2>New book</h2>
            <%= form_with model: @book do |f| %>
                Title <br />
                <%= f.text_field :title,class:'newbook__text' %><br />
                Opinion <br />
                <%= f.text_area :body,class:'newbook__text' %><br />
                <br />
                <%= f.submit 'Create Book',class:'btn btn-success' %>
            <% end  %>
        </div>
        <div class='col-md-8 offset-md-1'>
            <br />
            <h2>Books</h2>
            <table class='table table-stripe'>
                <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Opinion</th>
                </tr>
                <% @books.each do |book| %>
                    <tr>
                        <td>
                            <%= link_to user_path(book.user) do %>
                                <%= image_tag book.user.get_image(100,100) %>
                            <% end %>
                        </td>
                        <td><%= link_to book.title,book_path(book) %></td>
                        <td><%= book.body %></td>
                        <td>
                            <% if book.favorited_by?(current_user) %>
                                <p>
                                <%= link_to book_favorites_path(book), method: :delete do %>
                                    <i class="fa-solid fa-heart fas-heart-link"> <%= book.favorites.count %></i>
                                <% end %>
                                </p>
                            <% else %>
                                <p>
                                <%= link_to book_favorites_path(book), method: :post do %>
                                    <i class="fa-regular fa-heart"> <%= book.favorites.count %></i>
                                <% end %>
                                </p>
                            <% end %>
                        </td>
                        <td>コメント数：<%= book.book_comments.count %>
                    </tr>
                <% end %>
            </table>
        </div>
    </div>
</div>

app/views/books/show.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-md-3'>
            <%= render 'users/user',user:@user %>
            <h2>New book</h2>
            <% if @book.errors.any? %>
                <%= @book.errors.count %>件のエラーが発生しました
                <ul>
                    <% @book.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            <% end %>
            <%= form_with model: @new_book do |f| %>
                Title <br />
                <%= f.text_field :title,class:'newbook__text' %><br />
                Opinion <br />
                <%= f.text_area :body,class:'newbook__text' %><br />
                <br />
                <%= f.submit 'Create Book',class:'btn btn-success' %>
            <% end  %>
        </div>
        <div class='col-md-8 offset-md-1'>
            <br />
            <h2>Book detail</h2>
            <table class='table table-stripe'>
                <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Opinion</th>
                    <th></th>
                    <th></th>
                </tr>
                <tr>
                    <td>
                        <%= link_to user_path(@book.user) do %>
                            <%= image_tag @user.get_image(100,100) %>
                        <% end %>
                        <br />
                        <%= link_to @user.name,user_path(@book.user) %>
                    </td>
                    <td><%= link_to @book.title,book_path(@book) %></td>
                    <td><%= @book.body %></td>
                    <td>

                    <% if @book.favorited_by?(current_user) %>
                        <p>
                            <%= link_to book_favorites_path(@book), method: :delete do %>
                                <i class="fas fa-heart fas-heart-link"> <%= @book.favorites.count %></i>
                            <% end %>
                        </p>
                    <% else %>
                        <p>
                        <%= link_to book_favorites_path(@book), method: :post do %>
                            <i class="fa-regular fa-heart"> <%= @book.favorites.count %></i>
                        <% end %>
                        </p>
                    <% end %>



                    </td>
                    <td>コメント数：<%= @book.book_comments.count %></td>
                    <% if @book.user == current_user %>
                        <td><%= link_to 'Edit',edit_book_path(@book),class:'btn btn-success' %></td>
                        <td><%= link_to 'Destroy',book_path(@book),method: :delete,class:'btn btn-danger', data: { confirm: "本当に削除しますか？" } %></td>
                    <% end %>
                </tr>
            </table>

            <% @book.book_comments.each do |comment| %>
                <div class='book__show'>
                    <div class='book__show__left'>
                        <%= image_tag comment.user.get_image(30,30) %><br />
                        <%= link_to comment.user.name,user_path(comment.user) %>
                    </div>
                    <div class='book__show__center'>
                        <%= comment.comment %>
                    </div>
                    <% if comment.user == current_user %>
                        <div class='book__show__right'>
                            <%= link_to 'Destroy',book_book_comment_path(comment.book,comment),method: :delete,class:'btn btn-danger' %>
                        </div>
                    <% end %>
                </div>
            <% end %>

            <%= form_with model: [@book, @comment] do |f| %>
                <%= f.text_area :comment, rows: '5', class:'comment__text' %>
                <%= f.submit "送信" %>
            <% end %>
        </div>
    </div>
</div>

app/views/homes/about.html.erb
<div class='container'>
    </div class='row'>
    <br />
        <h2 class='top__copy'>welcome to <i class="fas fa-book"></i> <strong>Bookers!!</strong></h2>
        <p class='top__copy'>CopyRight Infratop.inc</p>
    </div>
</div>

app/views/homes/top.html.erb
<div class='container'>
    </div class='row'>
        <div class='col-md-5 top'>
        <br />
            <h2>welcome to <i class="fas fa-book"></i> <strong>Bookers!!</strong></h2>

            <div class='top__content'>
                In <i class="fas fa-book"></i> <strong>Bookers!!</strong>,<br />
                you can share and exchange your opinions , inpressions , and emotions<br />
                about various books!
            </div>
            <%= link_to 'Log in',new_user_session_path,class:'btn btn-info top__login' %><br />
            <%= link_to 'Sign up',new_user_registration_path,class:'btn btn-success top__signin' %>
        </div>
        <p class='top__copy'>CopyRight Infratop.inc</p>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel ="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">

  </head>

  <body>  
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <ul class='header__left'>
        <li class="nav-item">
          <%= link_to 'Bookers',root_path,class:'nav-item__link' %>
        </li>
      </ul>
      <ul class='header__right'>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to user_path(current_user),class:'nav-item__link' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to users_path,class:'nav-item__link' do %>
              <i class="fas fa-users"></i> Users
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to books_path,class:'nav-item__link' do %>
              <i class="fas fa-book-open"></i> Books
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path,class:'nav-item__link', method: :delete do %>
              <i class="fas fa-sign-out-alt"></i> Log out
            <% end %>
          </li>


        <% else %>
          <li class="nav-item">
            <%= link_to root_path,class:'nav-item__link' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to home_about_path,class:'nav-item__link' do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_registration_path,class:'nav-item__link' do %>
              <i class="fas fa-user-plus"></i> Sign up
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path,class:'nav-item__link' do %>
              <i class="fas fa-sign-in-alt"></i> Log in
            <% end %>
          </li>
        <% end %>
      </ul>
    </nav>  
    <%= flash[:notice] %>
    <%= yield %>
    
  </body>
</html>

app/views/users/_user.html.erb
<br />
<h2>User info</h2>
<%= image_tag user.get_image(100,100) %><br />

<table class="table">
    <tr>
        <td>name</td>
        <td><%= @user.name %></td>
    </tr>
    <tr>
        <td>introduction</td>
        <td><%= user.introduction %></td>
    </tr>
</table>
<%= link_to edit_user_path(@user),class:'btn btn-outline-secondary' do %>
    <i class='fas fa-user-cog'></i>
<% end %>
<br />

app/views/users/edit.html.erb
<br />
<div class='container'>
    <div class='row'>
        <div class='col-md-5 user__edit'>
            <h2>User info</h2>
            <% if @user.errors.any? %>
                <%= @user.errors.count %>件のエラーが発生しました
                <ul>
                    <% @user.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            <% end %>
            <%= form_with model: @user do |f| %> 
                Name<br />
                <%= f.text_field :name %><br />
                Image<br />
                <%= f.file_field :profile_image, accept: "image/*" %><br />                
                Introduction<br />
                <%= f.text_area :introduction %><br />

                <%= f.submit 'Update User' %>
            <% end %>
        </div>
    </div>
</div>

<br />
<p class='top__copy'>CopyRight Infratop.inc</p>

app/views/users/index.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-md-3'>
            <%= render 'user',user:@user %>
            <h2>New book</h2>
            <% if @book.errors.any? %>
                <%= @book.errors.count %>件のエラーが発生しました
                <ul>
                    <% @book.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            <% end %>
            <%= form_with model: @book do |f| %>
                Title <br />
                <%= f.text_field :title,class:'newbook__text' %><br />
                Opinion <br />
                <%= f.text_area :body,class:'newbook__text' %><br />
                <br />
                <%= f.submit 'Create Book',class:'btn btn-success' %>
            <% end  %>
        </div>
        <div class='col-md-8 offset-md-1'>
            <br />
            <h2>Users</h2>
            <table class='table table-stripe'>
                <tr>
                    <th>Image</th>
                    <th>name</th>
                    <th></th>
                </tr>
                <% @users.each do |user| %>
                    <tr>
                        <td>
                            <%= link_to user_path(user) do %>
                                <%= image_tag user.get_image(100,100) %>
                            <% end %>
                        </td>
                        <td><%= user.name %></td>
                        <td><%= link_to 'Show',user_path(user) %></td>
                    </tr>
                <% end %>
            </table>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-md-3'>
            <%= render 'user',user:@user %>
            <h2>New book</h2>
            <% if @book.errors.any? %>
                <%= @book.errors.count %>件のエラーが発生しました
                <ul>
                    <% @book.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            <% end %>
            <%= form_with model: @book do |f| %>
                Title <br />
                <%= f.text_field :title,class:'newbook__text' %><br />
                Opinion <br />
                <%= f.text_area :body,class:'newbook__text' %><br />
                <br />
                <%= f.submit 'Create Book',class:'btn btn-success' %>
            <% end  %>
        </div>
        <div class='col-md-8 offset-md-1'>
            <br />
            <h2>Books</h2>
            <table class='table table-stripe'>
                <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Opinion</th>
                    <th></th>
                </tr>
                <% @books.each do |book| %>
                    <tr>
                        <td>
                            <%= link_to user_path(book.user) do %>
                                <%= image_tag book.user.get_image(100,100) %>
                            <% end %>
                        </td>
                        <td><%= link_to book.title,book_path(book) %></td>
                        <td><%= book.body %></td>
                        <td>

                    <% if book.favorited_by?(current_user) %>
                        <p>
                            <%= link_to book_favorites_path(book), method: :delete do %>
                                <i class="fas fa-heart fas-heart-link"> <%= book.favorites.count %></i>
                            <% end %>
                        </p>
                    <% else %>
                        <p>
                        <%= link_to book_favorites_path(book), method: :post do %>
                            <i class="fa-regular fa-heart"> <%= book.favorites.count %></i>
                        <% end %>
                        </p>
                    <% end %>



                    </td>
                    </tr>
                <% end %>
            </table>
        </div>
    </div>
</div>